import { CalendarWrapper } from "@/components/CalendarWrapper"
import Head from "next/head"
import "react-big-calendar/lib/css/react-big-calendar.css"

export default function Home() {
  return (
    <>
      <Head>
        <title>Simple Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ height: "100vh" }}>
          <CalendarWrapper />
        </div>
      </main>
    </>
  )
}
