import { CalendarWrapper } from "@/components/CalendarWrapper"
import prisma from "@/lib/prisma"
import { Event } from "@prisma/client"
import { GetStaticProps } from "next"
import Head from "next/head"
import "react-big-calendar/lib/css/react-big-calendar.css"

export const getStaticProps: GetStaticProps = async () => {
  const events = await prisma.event.findMany()
  return {
    props: {
      // Using JSON parse and stringify to create a serializable object.
      events: JSON.parse(JSON.stringify(events)),
    },
  }
}

type Props = {
  events: Event[]
}

export default function Home({ events }: Props) {
  return (
    <>
      <Head>
        <title>Simple Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ height: "100vh" }}>
          <CalendarWrapper events={events} />
        </div>
      </main>
    </>
  )
}
